<?php

return [
    'defaults' => [
        'tenant' => [
            'palette' => 'salvia',
            'theme_mode' => 'light',
            'font_family' => 'manrope',
        ],
        'guest' => [
            'palette' => 'salvia',
            'theme_mode' => 'light',
            'font_family' => 'manrope',
        ],
    ],

    'superuser' => [
        'palette' => 'superuser',
        'theme_mode' => 'light',
        'font_family' => 'manrope',
    ],

    'themes' => [
        'light' => 'Chiaro',
        'dark' => 'Scuro',
    ],

    'fonts' => [
        'manrope' => [
            'label' => 'Manrope',
            'family' => 'Manrope',
        ],
        'dm_sans' => [
            'label' => 'DM Sans',
            'family' => 'DM Sans',
        ],
        'nunito' => [
            'label' => 'Nunito',
            'family' => 'Nunito',
        ],
        'source_sans_3' => [
            'label' => 'Source Sans 3',
            'family' => 'Source Sans 3',
        ],
        'merriweather_sans' => [
            'label' => 'Merriweather Sans',
            'family' => 'Merriweather Sans',
        ],
    ],

    'palettes' => [
        'salvia' => [
            'label' => 'Salvia',
            'light' => [
                'app_bg' => '#f4f6f1',
                'panel_bg' => '#ffffff',
                'panel_muted' => '#eef2e6',
                'topbar_bg' => '#fbfcf8',
                'topbar_text' => '#22301b',
                'sidebar_bg' => '#f7faf1',
                'sidebar_text' => '#314128',
                'border' => '#d8e2cf',
                'headline' => '#172111',
                'body_text' => '#43533a',
                'accent' => '#6f8c44',
                'accent_strong' => '#597234',
                'accent_soft' => '#dde8c8',
                'active_bg' => '#d7e4be',
                'active_text' => '#1d2a14',
                'pill_bg' => '#e7efda',
                'pill_text' => '#314526',
                'overlay' => 'rgba(111, 140, 68, 0.18)',
            ],
            'dark' => [
                'app_bg' => '#0f1510',
                'panel_bg' => '#151d15',
                'panel_muted' => '#1c251c',
                'topbar_bg' => '#131b13',
                'topbar_text' => '#eef6e6',
                'sidebar_bg' => '#101810',
                'sidebar_text' => '#dce8cd',
                'border' => '#2c3a29',
                'headline' => '#f5faef',
                'body_text' => '#c2cfb6',
                'accent' => '#93b45f',
                'accent_strong' => '#aacb75',
                'accent_soft' => '#24321d',
                'active_bg' => '#293a20',
                'active_text' => '#f3f9eb',
                'pill_bg' => '#22311c',
                'pill_text' => '#e2f0d0',
                'overlay' => 'rgba(147, 180, 95, 0.22)',
            ],
        ],
        'oceano' => [
            'label' => 'Oceano',
            'light' => [
                'app_bg' => '#f2f7f8',
                'panel_bg' => '#ffffff',
                'panel_muted' => '#e6eff1',
                'topbar_bg' => '#f9fcfd',
                'topbar_text' => '#17313a',
                'sidebar_bg' => '#f5fbfc',
                'sidebar_text' => '#234754',
                'border' => '#d2e1e6',
                'headline' => '#122630',
                'body_text' => '#42616b',
                'accent' => '#2f7a8a',
                'accent_strong' => '#255f6b',
                'accent_soft' => '#d2e8ee',
                'active_bg' => '#c7e3ea',
                'active_text' => '#16353f',
                'pill_bg' => '#deedf1',
                'pill_text' => '#244a57',
                'overlay' => 'rgba(47, 122, 138, 0.16)',
            ],
            'dark' => [
                'app_bg' => '#0d1518',
                'panel_bg' => '#132026',
                'panel_muted' => '#192931',
                'topbar_bg' => '#122027',
                'topbar_text' => '#ebf7f9',
                'sidebar_bg' => '#0f1a1f',
                'sidebar_text' => '#d6edf2',
                'border' => '#29404a',
                'headline' => '#f1fbfd',
                'body_text' => '#bfd7dc',
                'accent' => '#53a6b9',
                'accent_strong' => '#71bfd0',
                'accent_soft' => '#1d3640',
                'active_bg' => '#23414d',
                'active_text' => '#f0fbfd',
                'pill_bg' => '#1d3540',
                'pill_text' => '#d7f0f5',
                'overlay' => 'rgba(83, 166, 185, 0.2)',
            ],
        ],
        'ambra' => [
            'label' => 'Ambra',
            'light' => [
                'app_bg' => '#faf5ed',
                'panel_bg' => '#ffffff',
                'panel_muted' => '#f5ebdc',
                'topbar_bg' => '#fffaf2',
                'topbar_text' => '#3a2914',
                'sidebar_bg' => '#fff8ef',
                'sidebar_text' => '#5b4020',
                'border' => '#ecd8bd',
                'headline' => '#2e200f',
                'body_text' => '#70543a',
                'accent' => '#c0822b',
                'accent_strong' => '#9f6921',
                'accent_soft' => '#f3e1c6',
                'active_bg' => '#efd7ae',
                'active_text' => '#452d10',
                'pill_bg' => '#f6e5ca',
                'pill_text' => '#6f4b1f',
                'overlay' => 'rgba(192, 130, 43, 0.18)',
            ],
            'dark' => [
                'app_bg' => '#16110b',
                'panel_bg' => '#20170d',
                'panel_muted' => '#2a1d10',
                'topbar_bg' => '#21180e',
                'topbar_text' => '#fff5e6',
                'sidebar_bg' => '#1a130b',
                'sidebar_text' => '#f0ddbf',
                'border' => '#493420',
                'headline' => '#fff8ee',
                'body_text' => '#e0c7a3',
                'accent' => '#e2a04a',
                'accent_strong' => '#f0b968',
                'accent_soft' => '#3b2915',
                'active_bg' => '#4b3218',
                'active_text' => '#fff8ee',
                'pill_bg' => '#3b2915',
                'pill_text' => '#f7dfb8',
                'overlay' => 'rgba(226, 160, 74, 0.24)',
            ],
        ],
        'terracotta' => [
            'label' => 'Terracotta',
            'light' => [
                'app_bg' => '#fbf3f0',
                'panel_bg' => '#ffffff',
                'panel_muted' => '#f4e6e0',
                'topbar_bg' => '#fff9f7',
                'topbar_text' => '#3b241d',
                'sidebar_bg' => '#fff7f4',
                'sidebar_text' => '#5f382e',
                'border' => '#ebd3ca',
                'headline' => '#2f1c17',
                'body_text' => '#6f4b42',
                'accent' => '#b96a52',
                'accent_strong' => '#975240',
                'accent_soft' => '#f1d7ce',
                'active_bg' => '#ecc5b7',
                'active_text' => '#44231a',
                'pill_bg' => '#f4ddd5',
                'pill_text' => '#6b3f33',
                'overlay' => 'rgba(185, 106, 82, 0.18)',
            ],
            'dark' => [
                'app_bg' => '#17100e',
                'panel_bg' => '#201513',
                'panel_muted' => '#2a1c19',
                'topbar_bg' => '#201614',
                'topbar_text' => '#fff3ef',
                'sidebar_bg' => '#1a1210',
                'sidebar_text' => '#f1d6ce',
                'border' => '#4a2b24',
                'headline' => '#fff7f4',
                'body_text' => '#dfbdb3',
                'accent' => '#d8876b',
                'accent_strong' => '#eb9d84',
                'accent_soft' => '#3f2620',
                'active_bg' => '#4d2b23',
                'active_text' => '#fff7f4',
                'pill_bg' => '#402520',
                'pill_text' => '#f4d3c8',
                'overlay' => 'rgba(216, 135, 107, 0.24)',
            ],
        ],
        'ardesia' => [
            'label' => 'Ardesia',
            'light' => [
                'app_bg' => '#f3f5f7',
                'panel_bg' => '#ffffff',
                'panel_muted' => '#e7ebef',
                'topbar_bg' => '#fbfcfd',
                'topbar_text' => '#1e2c39',
                'sidebar_bg' => '#f7f9fb',
                'sidebar_text' => '#32485c',
                'border' => '#d4dde5',
                'headline' => '#15222d',
                'body_text' => '#4c6172',
                'accent' => '#5a7892',
                'accent_strong' => '#456076',
                'accent_soft' => '#d7e3ec',
                'active_bg' => '#cadbe8',
                'active_text' => '#1b3142',
                'pill_bg' => '#dfe8ef',
                'pill_text' => '#365066',
                'overlay' => 'rgba(90, 120, 146, 0.18)',
            ],
            'dark' => [
                'app_bg' => '#0e1419',
                'panel_bg' => '#141d24',
                'panel_muted' => '#1b2730',
                'topbar_bg' => '#162027',
                'topbar_text' => '#eef5fb',
                'sidebar_bg' => '#111920',
                'sidebar_text' => '#d9e6f2',
                'border' => '#2b3c49',
                'headline' => '#f7fbff',
                'body_text' => '#c0cfdb',
                'accent' => '#7ea4c5',
                'accent_strong' => '#98badd',
                'accent_soft' => '#20313d',
                'active_bg' => '#273b49',
                'active_text' => '#f6fbff',
                'pill_bg' => '#20323e',
                'pill_text' => '#dbeaf6',
                'overlay' => 'rgba(126, 164, 197, 0.24)',
            ],
        ],
        'bosco' => [
            'label' => 'Bosco',
            'light' => [
                'app_bg' => '#f2f5f2',
                'panel_bg' => '#ffffff',
                'panel_muted' => '#e3ebe5',
                'topbar_bg' => '#f9fbf9',
                'topbar_text' => '#183024',
                'sidebar_bg' => '#f4f8f5',
                'sidebar_text' => '#214735',
                'border' => '#cfddd4',
                'headline' => '#12261c',
                'body_text' => '#3a5c4b',
                'accent' => '#2f7d5c',
                'accent_strong' => '#215f44',
                'accent_soft' => '#cfe7dc',
                'active_bg' => '#c2e0d1',
                'active_text' => '#153729',
                'pill_bg' => '#d8ebdf',
                'pill_text' => '#24543e',
                'overlay' => 'rgba(47, 125, 92, 0.18)',
            ],
            'dark' => [
                'app_bg' => '#0d1511',
                'panel_bg' => '#13201a',
                'panel_muted' => '#1a2a22',
                'topbar_bg' => '#14221b',
                'topbar_text' => '#edf8f1',
                'sidebar_bg' => '#101b15',
                'sidebar_text' => '#d4ebdd',
                'border' => '#284234',
                'headline' => '#f4fcf7',
                'body_text' => '#b9d3c4',
                'accent' => '#4aa27b',
                'accent_strong' => '#67bd95',
                'accent_soft' => '#1d3529',
                'active_bg' => '#244235',
                'active_text' => '#f1fbf5',
                'pill_bg' => '#1e372b',
                'pill_text' => '#d8efe1',
                'overlay' => 'rgba(74, 162, 123, 0.22)',
            ],
        ],
        'superuser' => [
            'label' => 'Superuser',
            'light' => [
                'app_bg' => '#fff5df',
                'panel_bg' => '#fffdf9',
                'panel_muted' => '#fdf0d2',
                'topbar_bg' => '#fff7e5',
                'topbar_text' => '#4b2f04',
                'sidebar_bg' => '#fff9ec',
                'sidebar_text' => '#6f4307',
                'border' => '#f0d59f',
                'headline' => '#3c2404',
                'body_text' => '#7b5a27',
                'accent' => '#df9122',
                'accent_strong' => '#c27211',
                'accent_soft' => '#fde7bc',
                'active_bg' => '#fbdb95',
                'active_text' => '#5b3605',
                'pill_bg' => '#fde9bd',
                'pill_text' => '#7a4908',
                'overlay' => 'rgba(223, 145, 34, 0.24)',
            ],
            'dark' => [
                'app_bg' => '#1b1307',
                'panel_bg' => '#241809',
                'panel_muted' => '#2d1e0d',
                'topbar_bg' => '#291c0b',
                'topbar_text' => '#fff3dc',
                'sidebar_bg' => '#211607',
                'sidebar_text' => '#f6dfb0',
                'border' => '#62421b',
                'headline' => '#fff8ee',
                'body_text' => '#e1c793',
                'accent' => '#f0ab44',
                'accent_strong' => '#f8c066',
                'accent_soft' => '#433018',
                'active_bg' => '#56381a',
                'active_text' => '#fff8ee',
                'pill_bg' => '#493117',
                'pill_text' => '#ffe5b0',
                'overlay' => 'rgba(240, 171, 68, 0.28)',
            ],
        ],
    ],
];
